name: community_todo
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  provider: ^6.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_islamic.png" # Use your custom icon here

flutter:
  uses-material-design: true

  assets:
    - assets/quran/

  # Uncomment and add fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
